// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Data;

#nullable disable

namespace Warehouse.Data.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20250624204150_WarehouseStateDeletedElementReferenceOptional")]
    partial class WarehouseStateDeletedElementReferenceOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Data.Model.BuildingComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CatalogNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Warehouse.Data.Model.BuildingComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("MassInGrams")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInHungarianForints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");
                });

            modelBuilder.Entity("Warehouse.Data.Model.WarehouseStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangeTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ComponentCatalogNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("StateChanges");
                });

            modelBuilder.Entity("Warehouse.Data.Model.BuildingComponent", b =>
                {
                    b.HasOne("Warehouse.Data.Model.BuildingComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Warehouse.Data.Model.WarehouseStateChange", b =>
                {
                    b.HasOne("Warehouse.Data.Model.BuildingComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("Warehouse.Data.Model.BuildingComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId");

                    b.Navigation("Component");

                    b.Navigation("ComponentType");
                });
#pragma warning restore 612, 618
        }
    }
}
